app_secret: vvVs1SwCqVa8g4OPFag05j5hlf39cAlx
server:
  host: 127.0.0.1
  port: 50300

mysql: root:root@tcp(0.0.0.0:3306)/game

mongo:
  url: mongodb://root:example@localhost:27017/?authSource=admin
  db: local

grpc:
  email_sender:
    host: 127.0.0.1
    port: 50200
